name: Code Quality & Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest # Or a specific version
      - name: Run Biome Lint
        run: biome lint ./src
      - name: Run Biome Format Check
        run: biome format ./src

  test:
    runs-on: ubuntu-latest
    needs: lint-and-format # Ensures tests run after linting and formatting
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify a Node.js version compatible with Vitest
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
