name: Code Quality & Tests # Keeping this name as it accurately reflects both jobs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality: # Renamed job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest # Or a specific version
      - name: Run Biome Check # Consolidated lint and format check
        run: biome check ./src # This command checks both linting and formatting

  test:
    runs-on: ubuntu-latest
    needs: code-quality # Depends on the renamed job
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
